# Generated by Django 2.0.1 on 2018-04-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20180331_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
