# Generated by Django 2.0.1 on 2018-03-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20180316_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='involved_students', to='classroom.Course'),
        ),
    ]
