# Generated by Django 2.0.1 on 2018-03-27 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_auto_20180328_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='cls',
        ),
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
    ]
