# Generated by Django 2.0.1 on 2018-03-27 22:45

import classroom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_auto_20180328_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='user.png', upload_to=classroom.models.user_directory_path),
        ),
    ]
