# Generated by Django 2.0.1 on 2018-03-28 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0015_course_project_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='project',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='idea',
        ),
        migrations.RemoveField(
            model_name='studentsolution',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='studentsolution',
            name='student',
        ),
        migrations.RemoveField(
            model_name='takenproject',
            name='project',
        ),
        migrations.RemoveField(
            model_name='takenproject',
            name='student',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='student',
            name='projects',
        ),
        migrations.AddField(
            model_name='course',
            name='projects',
            field=models.ManyToManyField(related_name='projects', to='classroom.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='comments',
            field=models.CharField(default='', max_length=1000000),
        ),
        migrations.AddField(
            model_name='project',
            name='idea',
            field=models.CharField(default='', max_length=1000000),
        ),
        migrations.AddField(
            model_name='project',
            name='marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='marks_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='review',
            field=models.CharField(default='', max_length=1000000),
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Idea',
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
        migrations.DeleteModel(
            name='StudentSolution',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='TakenProject',
        ),
    ]
