# Generated by Django 2.0.1 on 2018-03-30 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0018_student_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='projects',
            field=models.ManyToManyField(related_name='course_projects', to='classroom.Project'),
        ),
    ]
