# Generated by Django 2.0.1 on 2018-03-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0019_auto_20180330_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='courseid',
            field=models.IntegerField(default=0),
        ),
    ]
