# Generated by Django 2.0.1 on 2018-03-30 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0020_project_courseid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='projects',
        ),
    ]
